faker.vehicle.bicycle() // 'Adventure Road Bicycle'
faker.vehicle.color() // 'red'
faker.vehicle.fuel() // 'Electric'
faker.vehicle.manufacturer() // 'Ford'
faker.vehicle.model() // 'Explorer'
faker.vehicle.type() // 'Coupe'
faker.vehicle.vehicle() // 'BMW Explorer'
faker.vehicle.vin() // 'YV1MH682762184654'
faker.vehicle.vrm() // 'MF56UPA'