
faker.animal.bear()
faker.animal.bird()
faker.animal.cat()
faker.animal.cetacean()
faker.animal.cow()
faker.animal.crocodilia()
faker.animal.dog()
faker.animal.fish()
faker.animal.horse()
faker.animal.insect()
faker.animal.lion()
faker.animal.rabbit()
faker.animal.rodent()
faker.animal.snake()
faker.animal.type()
